# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'DatawhaleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'SnapKit'
    pod 'Hero'
    pod 'lottie-ios'
    pod 'Moya/Combine'
    pod 'Moya'
    pod 'SwiftyJSON'
    pod 'ObjectMapper'
    pod 'SwiftDate'
    pod 'URLNavigator'
    pod 'ReSwift'
    pod 'SkeletonView'
  target 'DatawhaleAppTests' do
    inherit! :search_paths
  end

  target 'DatawhaleAppUITests' do
  end

end
